name: Issue report form
description: Create an issue report using a simple form
body:
  - type: markdown
    attributes:
      value: 'Thanks for taking the time to fill out this bug report!'
  - type: textarea
    id: issue
    attributes:
      label: Issue description
      description: 'Clear and detailed description of the issue.'
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: 'Do you know how to trigger this issue? Please walk us through it step by step.'
      placeholder: |
        1. Load attached save '...'
        2. Do xxx '....'
        3. Strange thing happens '...'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Game version and build number
      placeholder: v0.4.8 b208
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows
        - GeForce NOW
        - Linux
        - Mac OS
        - Other
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: |
          If applicable, attach a save file (zipped), screenshots, or log files.
          Saves and logs can be found at: ```%USERPROFILE%/AppData/Roaming/Captain of Industry```.
          On Linux, the ```%USERPROFILE%``` is usually ```~/.steam/steam/steamapps/compatdata/1594320/pfx/drive_c/users/steamuser/```.
          If you are reporting a crash or hardware issue, also include Unity logs from ```%USERPROFILE%/AppData/LocalLow/Mafi Games/Captain of Industry/``` and ```%USERPROFILE%/AppData/Local/Temp/Mafi Games/Captain of Industry/Crashes``` (zipped).
      placeholder: Attach files by clicking this area to highlight it and then dragging files in.
