name: Issue report form
description: File an issue report using a predefined form
body:
  - type: markdown
    attributes:
      value: 'Thanks for taking the time to fill out this bug report!'
  - type: textarea
    id: issue
    attributes:
      label: Issue description
      description: 'Clear and detailed description of the issue.'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: 'What did you expect to happen?'
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: 'Do you know how to trigger this issue? Please walk us through it step by step.'
      placeholder: |
        1. Load attached save '...'
        2. Do xxx '....'
        3. Strange thing happens '...'
  - type: input
    id: version
    attributes:
      label: Game version
      placeholder: v0.4.7c
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: >
          If applicable, attach a save file (zipped), screenshots, or log files to help us resolve the issue.
          You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`).
          If your issue is severe, like a crash or rendering glitches, also include Unity logs from
          `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`.
      placeholder: Attach files by clicking this area to highlight it and then dragging files in.
